### ISSUE TITLE
More of a feature request then an 'Issue'

### ISSUE THREAD

**Issue by Godrickharg** [MechTechnology/SmartStitch#2]
I've just discovered this project and I can see right now how its gonna save me HOURS of work, stupid minutia work.

That said, I have one request...  can you include a 'start numbering at' option?  MAYBE a 'ignore file' option?

The projects I am using this for often have the same first couple pages that I'd rather not have included in the larger scheme.  This would allow me to 'shift down' where the file breaks will be as well.  Example, if the files being joined has a chapter title and/or credits section that I would much rather have at the TOP of a file, rather than the end.  

The only other request might be to 'insert white space' of a certain length at a certain point.  I can see how difficult that might be however. ;)

**Comment by MechTechnology** [comment]
I want to help to let me a better understanding of the features you want:
1. You want some way to ignore some files from within the chapter folder? (so maybe a feild, where you can put the file names you want to ignore followed by a comma?) I think it's possible but i am just asking, isn't just taking them out the folder before running the stitcher an easier option?
2. about the insert white space, it seem tough considering how the software works, however can you elaborate with an example with that?

Thank you for your interest  in the my project, i hope you find it useful to you even in it's current form :D

**Comment by Thiemdes** [comment]
> 2. about the insert white space, it seem tough considering how the software works, however can you elaborate with an example with that?

Hello! I've been using this software for quite some time, perhaps since the very beginning? I had mistakenly downloaded the source code and you redirected me to the correct one on discord if you remember hahaha. Anyways, I think I might have a clue as to what they mean by that and I too would like to make the same request.

Taking webtoons as an example, you know how there's a considerable amount of white blank space in between panels? So upon stitching through this software, what it does is, it includes that whole white space at the end of a stitched page, and then the next page would start off with just 2px afar from the border, whereas It's preferable if it were somewhat evenly split between the two pages. 

I'm pretty bad at explaining so do refer to this [screenshot](https://i.imgur.com/YT58uIQ.png). Hopefully that helped, also thank you for your hard work on this, it's been a hell of a time saver, just amazing hahah.

**Comment by pepijnmm** [comment]
@MechTechnology she hasn't responded to your questions in 2+ months so it can be closed right?

**Comment by MechTechnology** [comment]
Yes they have not responded, and you can kind of get what you want by increasing the scan line value in the most recent version.
